version: '3.8'
services:
  report:
    build: .
    volumes:
      - './report.html:/root/aws-reporting/report.html'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    volumes:
      - './db/:/docker-entrypoint-initdb.d/:ro'
    environment:
      MYSQL_ROOT_PASSWORD: 'hunter2'
      MYSQL_DATABASE: 'aws_reporting'
